version: '3'
services:
  apache-shibd:
    image: sugwg/apache-shibd
    volumes:
      - ${PWD}/shibboleth:/mnt
    ports:
      - "${HOSTIP}:443:443"
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
